### ISSUE TITLE
error nil value

### ISSUE THREAD

**Issue by workino** [notdodo/conky_dodo#1]
```
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value

```
Hello,
when i try to use your skin i got these error. 
How can i solve it?

Thank

**Comment by notdodo** [comment]
Hi!

I cannot reproduce your issue...

I think it's a problem of your conky-lua lib. I use Arch Linux and the one from AUR: aur/conky-lua-archers 1.10.6-3.
Which distro do you use?

**Comment by Wayward1** [comment]
Hi, I get the same error using Linux Mint 18.2 with Conky 1.10.1 (the latest available for my distro). I assume I need to manually install the latest version of Conky? I'll go ahead and try that.

Edit: that didn't help. In addition, since updating, the background is no longer transparent, just black.

![screenshot from 2017-07-15 19-14-12](https://user-images.githubusercontent.com/8821916/28243290-7ca114e8-6992-11e7-836c-d948bd82c184.png)

**Comment by notdodo** [comment]
Did you changed the path to call the lua file?

https://github.com/edoz90/conky_dodo/blob/master/conky_dodoCPU#L55

[EDIT]
On ubuntu:
![conky](https://user-images.githubusercontent.com/6991986/28243352-8694b1a6-69c6-11e7-87da-3a128a95cf14.png)
![version](https://user-images.githubusercontent.com/6991986/28243353-88efafc8-69c6-11e7-8262-26a1a8ff2d40.png)

**Comment by Wayward1** [comment]
Like this? 
`lua_load = '/home/wayward_one/.conky/Dodo/dodo_ringsCPU.lua',`

No change. Conky-all is also the latest. (Sorry for my absence, I've been quite busy)

**Comment by notdodo** [comment]
Yes, I meant that path (if it is correct).

mmh..actually I don't know how to help you...

How do you start conky?

**Comment by Wayward1** [comment]
I've had conky itself start automatically as well as manually. I also have Conky Manager installed if that matters any, but Dodo doesn't show up in it.

**Comment by notdodo** [comment]
try with the provided script:
https://github.com/edoz90/conky_dodo/blob/master/conky-startup.sh

**Comment by Wayward1** [comment]
I've tried that too, same result.

**Comment by notdodo** [comment]
sorry I don't know how to help you further... Let me know if you have luck to solve this problem!

**Comment by Wayward1** [comment]
No problem, thanks for your time!

**Comment by notdodo** [comment]
try to write a simple hello world lua script and use it in a simple conky: just to see if the problem if from your library/conky version or mine version

**Comment by Wayward1** [comment]
Sorry, I don't know any programming languages yet :/ I'll let you know if I figure it out though
